### ISSUE TITLE
Revisit Giving

### ISSUE THREAD

**Issue by clarkmalmgren** [clarkmalmgren/bolingbrook-church#20]
Make portal that contains Adventist Giving, Easy Tithe, and Text to Donate.

**Comment by clarkmalmgren** [comment]
@jstphard

**Comment by Nalielle** [comment]
YES! We spoke about this yesterday. Really our giving page should reflect what our ways of giving are vs. what's on their right now. It should really look more like this (without stay social) we can keep images but ultimately have the different icons....
![ways to give](https://user-images.githubusercontent.com/30123695/28128783-910200a8-66f6-11e7-99de-268cc217968c.jpg)

For the envelope icon what would be cool is if they can have the option to give in person or have us mail them a giving envelope. I'm sure we probably wouldn't get much use from that but for our members who are not able to attend and rather send a check or something not sure if that's worth the effort but just a thought. 

If individuals can click on these icons on our giving page then we can add the different portals

**Comment by jstphard** [comment]
I love that idea. I'm working on some edits for each page that I'll have out by next tuesday that will include some edits (content wise) for giving, events, and our story pages!
