### ISSUE TITLE
Thumbnail & Edit

### ISSUE THREAD

**Issue by Nalielle** [clarkmalmgren/bolingbrook-church#85]
@clarkmalmgren Thumbnails need to be the image of the speaker. The last 3-4 weeks it's been the series image we need to change that. Also, we need the video clipped each week, the parameters are start at praise and worship and end with the end of sermon. We don't want to show countdown/announcements/worship in giving, etc. Sending a general email so they are aware as well.

**Comment by clarkmalmgren** [comment]
@Nalielle, I edited the last 6 weeks or so to reflect these changes. Closing out.
