### ISSUE TITLE
Friends and Family Sabbath Page

### ISSUE THREAD

**Issue by Nalielle** [clarkmalmgren/bolingbrook-church#86]
@clarkmalmgren can we get HOST video and HOST cards on the friends and family webpage available by Friday night.  I'll send you both via gmail. 

Thanks

**Comment by clarkmalmgren** [comment]
@Nalielle, the image wasn't super large, but it is deployed here: https://bolingbrook.church/friends-family-sabbath. Let me know if you want more changes beyond that.
